package com.minsal.dtic.sinavec.EntityDAO;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "BITACORA".
 */
@Entity
public class Bitacora {

    @Id(autoincrement = true)
    private Long id;
    private String operacion;
    private String sentenciaSql;
    private String nombreTabla;
    private Long idTablet;
    private String banderaEstado;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Bitacora() {
    }

    public Bitacora(Long id) {
        this.id = id;
    }

    @Generated
    public Bitacora(Long id, String operacion, String sentenciaSql, String nombreTabla, Long idTablet, String banderaEstado) {
        this.id = id;
        this.operacion = operacion;
        this.sentenciaSql = sentenciaSql;
        this.nombreTabla = nombreTabla;
        this.idTablet = idTablet;
        this.banderaEstado = banderaEstado;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOperacion() {
        return operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    public String getSentenciaSql() {
        return sentenciaSql;
    }

    public void setSentenciaSql(String sentenciaSql) {
        this.sentenciaSql = sentenciaSql;
    }

    public String getNombreTabla() {
        return nombreTabla;
    }

    public void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }

    public Long getIdTablet() {
        return idTablet;
    }

    public void setIdTablet(Long idTablet) {
        this.idTablet = idTablet;
    }

    public String getBanderaEstado() {
        return banderaEstado;
    }

    public void setBanderaEstado(String banderaEstado) {
        this.banderaEstado = banderaEstado;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
