package com.minsal.dtic.sinavec.EntityDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLAVE".
*/
public class ClaveDao extends AbstractDao<Clave, Long> {

    public static final String TABLENAME = "CLAVE";

    /**
     * Properties of entity Clave.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property IdDepartamento = new Property(1, Long.class, "idDepartamento", false, "ID_DEPARTAMENTO");
        public final static Property IdMunicipio = new Property(2, Long.class, "idMunicipio", false, "ID_MUNICIPIO");
        public final static Property Correlativo = new Property(3, Long.class, "correlativo", false, "CORRELATIVO");
        public final static Property Clave = new Property(4, String.class, "clave", false, "CLAVE");
        public final static Property IdProcedencia = new Property(5, long.class, "idProcedencia", false, "ID_PROCEDENCIA");
    }

    private DaoSession daoSession;


    public ClaveDao(DaoConfig config) {
        super(config);
    }
    
    public ClaveDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLAVE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_DEPARTAMENTO\" INTEGER," + // 1: idDepartamento
                "\"ID_MUNICIPIO\" INTEGER," + // 2: idMunicipio
                "\"CORRELATIVO\" INTEGER," + // 3: correlativo
                "\"CLAVE\" TEXT," + // 4: clave
                "\"ID_PROCEDENCIA\" INTEGER NOT NULL );"); // 5: idProcedencia
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLAVE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Clave entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long idDepartamento = entity.getIdDepartamento();
        if (idDepartamento != null) {
            stmt.bindLong(2, idDepartamento);
        }
 
        Long idMunicipio = entity.getIdMunicipio();
        if (idMunicipio != null) {
            stmt.bindLong(3, idMunicipio);
        }
 
        Long correlativo = entity.getCorrelativo();
        if (correlativo != null) {
            stmt.bindLong(4, correlativo);
        }
 
        String clave = entity.getClave();
        if (clave != null) {
            stmt.bindString(5, clave);
        }
        stmt.bindLong(6, entity.getIdProcedencia());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Clave entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long idDepartamento = entity.getIdDepartamento();
        if (idDepartamento != null) {
            stmt.bindLong(2, idDepartamento);
        }
 
        Long idMunicipio = entity.getIdMunicipio();
        if (idMunicipio != null) {
            stmt.bindLong(3, idMunicipio);
        }
 
        Long correlativo = entity.getCorrelativo();
        if (correlativo != null) {
            stmt.bindLong(4, correlativo);
        }
 
        String clave = entity.getClave();
        if (clave != null) {
            stmt.bindString(5, clave);
        }
        stmt.bindLong(6, entity.getIdProcedencia());
    }

    @Override
    protected final void attachEntity(Clave entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Clave readEntity(Cursor cursor, int offset) {
        Clave entity = new Clave( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // idDepartamento
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // idMunicipio
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // correlativo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // clave
            cursor.getLong(offset + 5) // idProcedencia
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Clave entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdDepartamento(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIdMunicipio(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setCorrelativo(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setClave(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIdProcedencia(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Clave entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Clave entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Clave entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCtlProcedenciaDao().getAllColumns());
            builder.append(" FROM CLAVE T");
            builder.append(" LEFT JOIN CTL_PROCEDENCIA T0 ON T.\"ID_PROCEDENCIA\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Clave loadCurrentDeep(Cursor cursor, boolean lock) {
        Clave entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CtlProcedencia ctlProcedencia = loadCurrentOther(daoSession.getCtlProcedenciaDao(), cursor, offset);
         if(ctlProcedencia != null) {
            entity.setCtlProcedencia(ctlProcedencia);
        }

        return entity;    
    }

    public Clave loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Clave> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Clave> list = new ArrayList<Clave>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Clave> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Clave> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
