package com.minsal.dtic.sinavec.EntityDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COLVOL_CALVE".
*/
public class ColvolCalveDao extends AbstractDao<ColvolCalve, Long> {

    public static final String TABLENAME = "COLVOL_CALVE";

    /**
     * Properties of entity ColvolCalve.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property IdClave = new Property(1, long.class, "idClave", false, "ID_CLAVE");
        public final static Property IdColvol = new Property(2, long.class, "idColvol", false, "ID_COLVOL");
    }

    private DaoSession daoSession;


    public ColvolCalveDao(DaoConfig config) {
        super(config);
    }
    
    public ColvolCalveDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COLVOL_CALVE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_CLAVE\" INTEGER NOT NULL ," + // 1: idClave
                "\"ID_COLVOL\" INTEGER NOT NULL ,"+"FOREIGN KEY(\"ID_CLAVE\")" +
                " REFERENCES CLAVE(\"ID\") ON DELETE CASCADE,"+"FOREIGN KEY(\"ID_COLVOL\")" +
                " REFERENCES PL_COLVOL(\"ID\") ON DELETE CASCADE );"); // 2: idColvol
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COLVOL_CALVE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ColvolCalve entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdClave());
        stmt.bindLong(3, entity.getIdColvol());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ColvolCalve entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdClave());
        stmt.bindLong(3, entity.getIdColvol());
    }

    @Override
    protected final void attachEntity(ColvolCalve entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ColvolCalve readEntity(Cursor cursor, int offset) {
        ColvolCalve entity = new ColvolCalve( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idClave
            cursor.getLong(offset + 2) // idColvol
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ColvolCalve entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdClave(cursor.getLong(offset + 1));
        entity.setIdColvol(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ColvolCalve entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ColvolCalve entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ColvolCalve entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getClaveDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPlColvolDao().getAllColumns());
            builder.append(" FROM COLVOL_CALVE T");
            builder.append(" LEFT JOIN CLAVE T0 ON T.\"ID_CLAVE\"=T0.\"ID\"");
            builder.append(" LEFT JOIN PL_COLVOL T1 ON T.\"ID_COLVOL\"=T1.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ColvolCalve loadCurrentDeep(Cursor cursor, boolean lock) {
        ColvolCalve entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Clave clave = loadCurrentOther(daoSession.getClaveDao(), cursor, offset);
         if(clave != null) {
            entity.setClave(clave);
        }
        offset += daoSession.getClaveDao().getAllColumns().length;

        PlColvol plColvol = loadCurrentOther(daoSession.getPlColvolDao(), cursor, offset);
         if(plColvol != null) {
            entity.setPlColvol(plColvol);
        }

        return entity;    
    }

    public ColvolCalve loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ColvolCalve> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ColvolCalve> list = new ArrayList<ColvolCalve>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ColvolCalve> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ColvolCalve> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
