package com.minsal.dtic.sinavec.EntityDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CTL_CASERIO".
*/
public class CtlCaserioDao extends AbstractDao<CtlCaserio, Long> {

    public static final String TABLENAME = "CTL_CASERIO";

    /**
     * Properties of entity CtlCaserio.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property IdDeptoApoyo = new Property(2, Long.class, "idDeptoApoyo", false, "ID_DEPTO_APOYO");
        public final static Property Bandera = new Property(3, Integer.class, "bandera", false, "BANDERA");
        public final static Property IdCanton = new Property(4, long.class, "idCanton", false, "ID_CANTON");
    }

    private DaoSession daoSession;


    public CtlCaserioDao(DaoConfig config) {
        super(config);
    }
    
    public CtlCaserioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CTL_CASERIO\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NOMBRE\" TEXT," + // 1: nombre
                "\"ID_DEPTO_APOYO\" INTEGER," + // 2: idDeptoApoyo
                "\"BANDERA\" INTEGER," + // 3: bandera
                "\"ID_CANTON\" INTEGER NOT NULL,"+"FOREIGN KEY(\"ID_CANTON\")" +
                " REFERENCES CTL_CANTON(\"ID\") ON DELETE CASCADE );"); // 4: idCanton
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CTL_CASERIO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CtlCaserio entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        Long idDeptoApoyo = entity.getIdDeptoApoyo();
        if (idDeptoApoyo != null) {
            stmt.bindLong(3, idDeptoApoyo);
        }
 
        Integer bandera = entity.getBandera();
        if (bandera != null) {
            stmt.bindLong(4, bandera);
        }
        stmt.bindLong(5, entity.getIdCanton());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CtlCaserio entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        Long idDeptoApoyo = entity.getIdDeptoApoyo();
        if (idDeptoApoyo != null) {
            stmt.bindLong(3, idDeptoApoyo);
        }
 
        Integer bandera = entity.getBandera();
        if (bandera != null) {
            stmt.bindLong(4, bandera);
        }
        stmt.bindLong(5, entity.getIdCanton());
    }

    @Override
    protected final void attachEntity(CtlCaserio entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CtlCaserio readEntity(Cursor cursor, int offset) {
        CtlCaserio entity = new CtlCaserio( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombre
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // idDeptoApoyo
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // bandera
            cursor.getLong(offset + 4) // idCanton
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CtlCaserio entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIdDeptoApoyo(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBandera(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setIdCanton(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CtlCaserio entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CtlCaserio entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CtlCaserio entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCtlCantonDao().getAllColumns());
            builder.append(" FROM CTL_CASERIO T");
            builder.append(" LEFT JOIN CTL_CANTON T0 ON T.\"ID_CANTON\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CtlCaserio loadCurrentDeep(Cursor cursor, boolean lock) {
        CtlCaserio entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CtlCanton ctlCanton = loadCurrentOther(daoSession.getCtlCantonDao(), cursor, offset);
         if(ctlCanton != null) {
            entity.setCtlCanton(ctlCanton);
        }

        return entity;    
    }

    public CtlCaserio loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CtlCaserio> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CtlCaserio> list = new ArrayList<CtlCaserio>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CtlCaserio> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CtlCaserio> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
