//clase
package com.minsal.dtic.sinavec.EntityDAO;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CTL_SEMANA_EPI".
 */
@Entity
public class CtlSemanaEpi implements Serializable {

    @Id
    private Long id;
    private Integer anio;
    private Integer semana;
    private String fechaInicio;
    private String fechaFin;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public CtlSemanaEpi() {
    }

    public CtlSemanaEpi(Long id) {
        this.id = id;
    }

    @Generated
    public CtlSemanaEpi(Long id, Integer anio, Integer semana, String fechaInicio, String fechaFin) {
        this.id = id;
        this.anio = anio;
        this.semana = semana;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAnio() {
        return anio;
    }

    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    public Integer getSemana() {
        return semana;
    }

    public void setSemana(Integer semana) {
        this.semana = semana;
    }

    public String getFechaInicio() {
        return fechaInicio;
    }

    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public String getFechaFin() {
        return fechaFin;
    }

    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}