package com.minsal.dtic.sinavec.EntityDAO;

import org.greenrobot.greendao.annotation.*;

import com.minsal.dtic.sinavec.EntityDAO.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CTL_TIPO_ESTABLECIMIENTO".
 */
@Entity(active = true)
public class CtlTipoEstablecimiento {

    @Id
    private Long id;
    private String nombre;
    private long idInstitucion;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient CtlTipoEstablecimientoDao myDao;

    @ToOne(joinProperty = "idInstitucion")
    private CtlInstitucion ctlInstitucion;

    @Generated
    private transient Long ctlInstitucion__resolvedKey;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public CtlTipoEstablecimiento() {
    }

    public CtlTipoEstablecimiento(Long id) {
        this.id = id;
    }

    @Generated
    public CtlTipoEstablecimiento(Long id, String nombre, long idInstitucion) {
        this.id = id;
        this.nombre = nombre;
        this.idInstitucion = idInstitucion;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCtlTipoEstablecimientoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public long getIdInstitucion() {
        return idInstitucion;
    }

    public void setIdInstitucion(long idInstitucion) {
        this.idInstitucion = idInstitucion;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public CtlInstitucion getCtlInstitucion() {
        long __key = this.idInstitucion;
        if (ctlInstitucion__resolvedKey == null || !ctlInstitucion__resolvedKey.equals(__key)) {
            __throwIfDetached();
            CtlInstitucionDao targetDao = daoSession.getCtlInstitucionDao();
            CtlInstitucion ctlInstitucionNew = targetDao.load(__key);
            synchronized (this) {
                ctlInstitucion = ctlInstitucionNew;
            	ctlInstitucion__resolvedKey = __key;
            }
        }
        return ctlInstitucion;
    }

    @Generated
    public void setCtlInstitucion(CtlInstitucion ctlInstitucion) {
        if (ctlInstitucion == null) {
            throw new DaoException("To-one property 'idInstitucion' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ctlInstitucion = ctlInstitucion;
            idInstitucion = ctlInstitucion.getId();
            ctlInstitucion__resolvedKey = idInstitucion;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
