package com.minsal.dtic.sinavec.EntityDAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.minsal.dtic.sinavec.EntityDAO.CtlProcedencia;
import com.minsal.dtic.sinavec.EntityDAO.Clave;
import com.minsal.dtic.sinavec.EntityDAO.CtlPais;
import com.minsal.dtic.sinavec.EntityDAO.CtlDepartamento;
import com.minsal.dtic.sinavec.EntityDAO.CtlMunicipio;
import com.minsal.dtic.sinavec.EntityDAO.CtlCanton;
import com.minsal.dtic.sinavec.EntityDAO.CtlCaserio;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoCaptura;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoActividad;
import com.minsal.dtic.sinavec.EntityDAO.CtlInstitucion;
import com.minsal.dtic.sinavec.EntityDAO.CtlTipoEstablecimiento;
import com.minsal.dtic.sinavec.EntityDAO.CtlEstablecimiento;
import com.minsal.dtic.sinavec.EntityDAO.FosUserUser;
import com.minsal.dtic.sinavec.EntityDAO.PlColvol;
import com.minsal.dtic.sinavec.EntityDAO.ColvolCalve;
import com.minsal.dtic.sinavec.EntityDAO.EstablecimientoClave;
import com.minsal.dtic.sinavec.EntityDAO.PromotorClave;
import com.minsal.dtic.sinavec.EntityDAO.CtlSemanaEpi;
import com.minsal.dtic.sinavec.EntityDAO.CtlTablet;
import com.minsal.dtic.sinavec.EntityDAO.Bitacora;
import com.minsal.dtic.sinavec.EntityDAO.CtlPlCriadero;
import com.minsal.dtic.sinavec.EntityDAO.CtlPlCriaderoTmp;
import com.minsal.dtic.sinavec.EntityDAO.PlCapturaAnopheles;
import com.minsal.dtic.sinavec.EntityDAO.PlSeguimientoBotiquin;
import com.minsal.dtic.sinavec.EntityDAO.PlPesquisaLarvaria;

import com.minsal.dtic.sinavec.EntityDAO.CtlProcedenciaDao;
import com.minsal.dtic.sinavec.EntityDAO.ClaveDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlPaisDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlDepartamentoDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlMunicipioDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlCantonDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlCaserioDao;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoCapturaDao;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoActividadDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlInstitucionDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlTipoEstablecimientoDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlEstablecimientoDao;
import com.minsal.dtic.sinavec.EntityDAO.FosUserUserDao;
import com.minsal.dtic.sinavec.EntityDAO.PlColvolDao;
import com.minsal.dtic.sinavec.EntityDAO.ColvolCalveDao;
import com.minsal.dtic.sinavec.EntityDAO.EstablecimientoClaveDao;
import com.minsal.dtic.sinavec.EntityDAO.PromotorClaveDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlSemanaEpiDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlTabletDao;
import com.minsal.dtic.sinavec.EntityDAO.BitacoraDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlPlCriaderoDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlPlCriaderoTmpDao;
import com.minsal.dtic.sinavec.EntityDAO.PlCapturaAnophelesDao;
import com.minsal.dtic.sinavec.EntityDAO.PlSeguimientoBotiquinDao;
import com.minsal.dtic.sinavec.EntityDAO.PlPesquisaLarvariaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ctlProcedenciaDaoConfig;
    private final DaoConfig claveDaoConfig;
    private final DaoConfig ctlPaisDaoConfig;
    private final DaoConfig ctlDepartamentoDaoConfig;
    private final DaoConfig ctlMunicipioDaoConfig;
    private final DaoConfig ctlCantonDaoConfig;
    private final DaoConfig ctlCaserioDaoConfig;
    private final DaoConfig plTipoCapturaDaoConfig;
    private final DaoConfig plTipoActividadDaoConfig;
    private final DaoConfig ctlInstitucionDaoConfig;
    private final DaoConfig ctlTipoEstablecimientoDaoConfig;
    private final DaoConfig ctlEstablecimientoDaoConfig;
    private final DaoConfig fosUserUserDaoConfig;
    private final DaoConfig plColvolDaoConfig;
    private final DaoConfig colvolCalveDaoConfig;
    private final DaoConfig establecimientoClaveDaoConfig;
    private final DaoConfig promotorClaveDaoConfig;
    private final DaoConfig ctlSemanaEpiDaoConfig;
    private final DaoConfig ctlTabletDaoConfig;
    private final DaoConfig bitacoraDaoConfig;
    private final DaoConfig ctlPlCriaderoDaoConfig;
    private final DaoConfig ctlPlCriaderoTmpDaoConfig;
    private final DaoConfig plCapturaAnophelesDaoConfig;
    private final DaoConfig plSeguimientoBotiquinDaoConfig;
    private final DaoConfig plPesquisaLarvariaDaoConfig;

    private final CtlProcedenciaDao ctlProcedenciaDao;
    private final ClaveDao claveDao;
    private final CtlPaisDao ctlPaisDao;
    private final CtlDepartamentoDao ctlDepartamentoDao;
    private final CtlMunicipioDao ctlMunicipioDao;
    private final CtlCantonDao ctlCantonDao;
    private final CtlCaserioDao ctlCaserioDao;
    private final PlTipoCapturaDao plTipoCapturaDao;
    private final PlTipoActividadDao plTipoActividadDao;
    private final CtlInstitucionDao ctlInstitucionDao;
    private final CtlTipoEstablecimientoDao ctlTipoEstablecimientoDao;
    private final CtlEstablecimientoDao ctlEstablecimientoDao;
    private final FosUserUserDao fosUserUserDao;
    private final PlColvolDao plColvolDao;
    private final ColvolCalveDao colvolCalveDao;
    private final EstablecimientoClaveDao establecimientoClaveDao;
    private final PromotorClaveDao promotorClaveDao;
    private final CtlSemanaEpiDao ctlSemanaEpiDao;
    private final CtlTabletDao ctlTabletDao;
    private final BitacoraDao bitacoraDao;
    private final CtlPlCriaderoDao ctlPlCriaderoDao;
    private final CtlPlCriaderoTmpDao ctlPlCriaderoTmpDao;
    private final PlCapturaAnophelesDao plCapturaAnophelesDao;
    private final PlSeguimientoBotiquinDao plSeguimientoBotiquinDao;
    private final PlPesquisaLarvariaDao plPesquisaLarvariaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ctlProcedenciaDaoConfig = daoConfigMap.get(CtlProcedenciaDao.class).clone();
        ctlProcedenciaDaoConfig.initIdentityScope(type);

        claveDaoConfig = daoConfigMap.get(ClaveDao.class).clone();
        claveDaoConfig.initIdentityScope(type);

        ctlPaisDaoConfig = daoConfigMap.get(CtlPaisDao.class).clone();
        ctlPaisDaoConfig.initIdentityScope(type);

        ctlDepartamentoDaoConfig = daoConfigMap.get(CtlDepartamentoDao.class).clone();
        ctlDepartamentoDaoConfig.initIdentityScope(type);

        ctlMunicipioDaoConfig = daoConfigMap.get(CtlMunicipioDao.class).clone();
        ctlMunicipioDaoConfig.initIdentityScope(type);

        ctlCantonDaoConfig = daoConfigMap.get(CtlCantonDao.class).clone();
        ctlCantonDaoConfig.initIdentityScope(type);

        ctlCaserioDaoConfig = daoConfigMap.get(CtlCaserioDao.class).clone();
        ctlCaserioDaoConfig.initIdentityScope(type);

        plTipoCapturaDaoConfig = daoConfigMap.get(PlTipoCapturaDao.class).clone();
        plTipoCapturaDaoConfig.initIdentityScope(type);

        plTipoActividadDaoConfig = daoConfigMap.get(PlTipoActividadDao.class).clone();
        plTipoActividadDaoConfig.initIdentityScope(type);

        ctlInstitucionDaoConfig = daoConfigMap.get(CtlInstitucionDao.class).clone();
        ctlInstitucionDaoConfig.initIdentityScope(type);

        ctlTipoEstablecimientoDaoConfig = daoConfigMap.get(CtlTipoEstablecimientoDao.class).clone();
        ctlTipoEstablecimientoDaoConfig.initIdentityScope(type);

        ctlEstablecimientoDaoConfig = daoConfigMap.get(CtlEstablecimientoDao.class).clone();
        ctlEstablecimientoDaoConfig.initIdentityScope(type);

        fosUserUserDaoConfig = daoConfigMap.get(FosUserUserDao.class).clone();
        fosUserUserDaoConfig.initIdentityScope(type);

        plColvolDaoConfig = daoConfigMap.get(PlColvolDao.class).clone();
        plColvolDaoConfig.initIdentityScope(type);

        colvolCalveDaoConfig = daoConfigMap.get(ColvolCalveDao.class).clone();
        colvolCalveDaoConfig.initIdentityScope(type);

        establecimientoClaveDaoConfig = daoConfigMap.get(EstablecimientoClaveDao.class).clone();
        establecimientoClaveDaoConfig.initIdentityScope(type);

        promotorClaveDaoConfig = daoConfigMap.get(PromotorClaveDao.class).clone();
        promotorClaveDaoConfig.initIdentityScope(type);

        ctlSemanaEpiDaoConfig = daoConfigMap.get(CtlSemanaEpiDao.class).clone();
        ctlSemanaEpiDaoConfig.initIdentityScope(type);

        ctlTabletDaoConfig = daoConfigMap.get(CtlTabletDao.class).clone();
        ctlTabletDaoConfig.initIdentityScope(type);

        bitacoraDaoConfig = daoConfigMap.get(BitacoraDao.class).clone();
        bitacoraDaoConfig.initIdentityScope(type);

        ctlPlCriaderoDaoConfig = daoConfigMap.get(CtlPlCriaderoDao.class).clone();
        ctlPlCriaderoDaoConfig.initIdentityScope(type);

        ctlPlCriaderoTmpDaoConfig = daoConfigMap.get(CtlPlCriaderoTmpDao.class).clone();
        ctlPlCriaderoTmpDaoConfig.initIdentityScope(type);

        plCapturaAnophelesDaoConfig = daoConfigMap.get(PlCapturaAnophelesDao.class).clone();
        plCapturaAnophelesDaoConfig.initIdentityScope(type);

        plSeguimientoBotiquinDaoConfig = daoConfigMap.get(PlSeguimientoBotiquinDao.class).clone();
        plSeguimientoBotiquinDaoConfig.initIdentityScope(type);

        plPesquisaLarvariaDaoConfig = daoConfigMap.get(PlPesquisaLarvariaDao.class).clone();
        plPesquisaLarvariaDaoConfig.initIdentityScope(type);

        ctlProcedenciaDao = new CtlProcedenciaDao(ctlProcedenciaDaoConfig, this);
        claveDao = new ClaveDao(claveDaoConfig, this);
        ctlPaisDao = new CtlPaisDao(ctlPaisDaoConfig, this);
        ctlDepartamentoDao = new CtlDepartamentoDao(ctlDepartamentoDaoConfig, this);
        ctlMunicipioDao = new CtlMunicipioDao(ctlMunicipioDaoConfig, this);
        ctlCantonDao = new CtlCantonDao(ctlCantonDaoConfig, this);
        ctlCaserioDao = new CtlCaserioDao(ctlCaserioDaoConfig, this);
        plTipoCapturaDao = new PlTipoCapturaDao(plTipoCapturaDaoConfig, this);
        plTipoActividadDao = new PlTipoActividadDao(plTipoActividadDaoConfig, this);
        ctlInstitucionDao = new CtlInstitucionDao(ctlInstitucionDaoConfig, this);
        ctlTipoEstablecimientoDao = new CtlTipoEstablecimientoDao(ctlTipoEstablecimientoDaoConfig, this);
        ctlEstablecimientoDao = new CtlEstablecimientoDao(ctlEstablecimientoDaoConfig, this);
        fosUserUserDao = new FosUserUserDao(fosUserUserDaoConfig, this);
        plColvolDao = new PlColvolDao(plColvolDaoConfig, this);
        colvolCalveDao = new ColvolCalveDao(colvolCalveDaoConfig, this);
        establecimientoClaveDao = new EstablecimientoClaveDao(establecimientoClaveDaoConfig, this);
        promotorClaveDao = new PromotorClaveDao(promotorClaveDaoConfig, this);
        ctlSemanaEpiDao = new CtlSemanaEpiDao(ctlSemanaEpiDaoConfig, this);
        ctlTabletDao = new CtlTabletDao(ctlTabletDaoConfig, this);
        bitacoraDao = new BitacoraDao(bitacoraDaoConfig, this);
        ctlPlCriaderoDao = new CtlPlCriaderoDao(ctlPlCriaderoDaoConfig, this);
        ctlPlCriaderoTmpDao = new CtlPlCriaderoTmpDao(ctlPlCriaderoTmpDaoConfig, this);
        plCapturaAnophelesDao = new PlCapturaAnophelesDao(plCapturaAnophelesDaoConfig, this);
        plSeguimientoBotiquinDao = new PlSeguimientoBotiquinDao(plSeguimientoBotiquinDaoConfig, this);
        plPesquisaLarvariaDao = new PlPesquisaLarvariaDao(plPesquisaLarvariaDaoConfig, this);

        registerDao(CtlProcedencia.class, ctlProcedenciaDao);
        registerDao(Clave.class, claveDao);
        registerDao(CtlPais.class, ctlPaisDao);
        registerDao(CtlDepartamento.class, ctlDepartamentoDao);
        registerDao(CtlMunicipio.class, ctlMunicipioDao);
        registerDao(CtlCanton.class, ctlCantonDao);
        registerDao(CtlCaserio.class, ctlCaserioDao);
        registerDao(PlTipoCaptura.class, plTipoCapturaDao);
        registerDao(PlTipoActividad.class, plTipoActividadDao);
        registerDao(CtlInstitucion.class, ctlInstitucionDao);
        registerDao(CtlTipoEstablecimiento.class, ctlTipoEstablecimientoDao);
        registerDao(CtlEstablecimiento.class, ctlEstablecimientoDao);
        registerDao(FosUserUser.class, fosUserUserDao);
        registerDao(PlColvol.class, plColvolDao);
        registerDao(ColvolCalve.class, colvolCalveDao);
        registerDao(EstablecimientoClave.class, establecimientoClaveDao);
        registerDao(PromotorClave.class, promotorClaveDao);
        registerDao(CtlSemanaEpi.class, ctlSemanaEpiDao);
        registerDao(CtlTablet.class, ctlTabletDao);
        registerDao(Bitacora.class, bitacoraDao);
        registerDao(CtlPlCriadero.class, ctlPlCriaderoDao);
        registerDao(CtlPlCriaderoTmp.class, ctlPlCriaderoTmpDao);
        registerDao(PlCapturaAnopheles.class, plCapturaAnophelesDao);
        registerDao(PlSeguimientoBotiquin.class, plSeguimientoBotiquinDao);
        registerDao(PlPesquisaLarvaria.class, plPesquisaLarvariaDao);
    }
    
    public void clear() {
        ctlProcedenciaDaoConfig.clearIdentityScope();
        claveDaoConfig.clearIdentityScope();
        ctlPaisDaoConfig.clearIdentityScope();
        ctlDepartamentoDaoConfig.clearIdentityScope();
        ctlMunicipioDaoConfig.clearIdentityScope();
        ctlCantonDaoConfig.clearIdentityScope();
        ctlCaserioDaoConfig.clearIdentityScope();
        plTipoCapturaDaoConfig.clearIdentityScope();
        plTipoActividadDaoConfig.clearIdentityScope();
        ctlInstitucionDaoConfig.clearIdentityScope();
        ctlTipoEstablecimientoDaoConfig.clearIdentityScope();
        ctlEstablecimientoDaoConfig.clearIdentityScope();
        fosUserUserDaoConfig.clearIdentityScope();
        plColvolDaoConfig.clearIdentityScope();
        colvolCalveDaoConfig.clearIdentityScope();
        establecimientoClaveDaoConfig.clearIdentityScope();
        promotorClaveDaoConfig.clearIdentityScope();
        ctlSemanaEpiDaoConfig.clearIdentityScope();
        ctlTabletDaoConfig.clearIdentityScope();
        bitacoraDaoConfig.clearIdentityScope();
        ctlPlCriaderoDaoConfig.clearIdentityScope();
        ctlPlCriaderoTmpDaoConfig.clearIdentityScope();
        plCapturaAnophelesDaoConfig.clearIdentityScope();
        plSeguimientoBotiquinDaoConfig.clearIdentityScope();
        plPesquisaLarvariaDaoConfig.clearIdentityScope();
    }

    public CtlProcedenciaDao getCtlProcedenciaDao() {
        return ctlProcedenciaDao;
    }

    public ClaveDao getClaveDao() {
        return claveDao;
    }

    public CtlPaisDao getCtlPaisDao() {
        return ctlPaisDao;
    }

    public CtlDepartamentoDao getCtlDepartamentoDao() {
        return ctlDepartamentoDao;
    }

    public CtlMunicipioDao getCtlMunicipioDao() {
        return ctlMunicipioDao;
    }

    public CtlCantonDao getCtlCantonDao() {
        return ctlCantonDao;
    }

    public CtlCaserioDao getCtlCaserioDao() {
        return ctlCaserioDao;
    }

    public PlTipoCapturaDao getPlTipoCapturaDao() {
        return plTipoCapturaDao;
    }

    public PlTipoActividadDao getPlTipoActividadDao() {
        return plTipoActividadDao;
    }

    public CtlInstitucionDao getCtlInstitucionDao() {
        return ctlInstitucionDao;
    }

    public CtlTipoEstablecimientoDao getCtlTipoEstablecimientoDao() {
        return ctlTipoEstablecimientoDao;
    }

    public CtlEstablecimientoDao getCtlEstablecimientoDao() {
        return ctlEstablecimientoDao;
    }

    public FosUserUserDao getFosUserUserDao() {
        return fosUserUserDao;
    }

    public PlColvolDao getPlColvolDao() {
        return plColvolDao;
    }

    public ColvolCalveDao getColvolCalveDao() {
        return colvolCalveDao;
    }

    public EstablecimientoClaveDao getEstablecimientoClaveDao() {
        return establecimientoClaveDao;
    }

    public PromotorClaveDao getPromotorClaveDao() {
        return promotorClaveDao;
    }

    public CtlSemanaEpiDao getCtlSemanaEpiDao() {
        return ctlSemanaEpiDao;
    }

    public CtlTabletDao getCtlTabletDao() {
        return ctlTabletDao;
    }

    public BitacoraDao getBitacoraDao() {
        return bitacoraDao;
    }

    public CtlPlCriaderoDao getCtlPlCriaderoDao() {
        return ctlPlCriaderoDao;
    }

    public CtlPlCriaderoTmpDao getCtlPlCriaderoTmpDao() {
        return ctlPlCriaderoTmpDao;
    }

    public PlCapturaAnophelesDao getPlCapturaAnophelesDao() {
        return plCapturaAnophelesDao;
    }

    public PlSeguimientoBotiquinDao getPlSeguimientoBotiquinDao() {
        return plSeguimientoBotiquinDao;
    }

    public PlPesquisaLarvariaDao getPlPesquisaLarvariaDao() {
        return plPesquisaLarvariaDao;
    }

}
