package com.minsal.dtic.sinavec.EntityDAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.minsal.dtic.sinavec.EntityDAO.User;
import com.minsal.dtic.sinavec.EntityDAO.Bitacora;
import com.minsal.dtic.sinavec.EntityDAO.CtlProcedencia;
import com.minsal.dtic.sinavec.EntityDAO.Clave;
import com.minsal.dtic.sinavec.EntityDAO.CtlPais;
import com.minsal.dtic.sinavec.EntityDAO.CtlDepartamento;
import com.minsal.dtic.sinavec.EntityDAO.CtlMunicipio;
import com.minsal.dtic.sinavec.EntityDAO.CtlCanton;
import com.minsal.dtic.sinavec.EntityDAO.CtlCaserio;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoCaptura;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoActividad;
import com.minsal.dtic.sinavec.EntityDAO.CtlInstitucion;
import com.minsal.dtic.sinavec.EntityDAO.CtlTipoEstablecimiento;
import com.minsal.dtic.sinavec.EntityDAO.CtlEstablecimiento;

import com.minsal.dtic.sinavec.EntityDAO.UserDao;
import com.minsal.dtic.sinavec.EntityDAO.BitacoraDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlProcedenciaDao;
import com.minsal.dtic.sinavec.EntityDAO.ClaveDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlPaisDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlDepartamentoDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlMunicipioDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlCantonDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlCaserioDao;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoCapturaDao;
import com.minsal.dtic.sinavec.EntityDAO.PlTipoActividadDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlInstitucionDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlTipoEstablecimientoDao;
import com.minsal.dtic.sinavec.EntityDAO.CtlEstablecimientoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig bitacoraDaoConfig;
    private final DaoConfig ctlProcedenciaDaoConfig;
    private final DaoConfig claveDaoConfig;
    private final DaoConfig ctlPaisDaoConfig;
    private final DaoConfig ctlDepartamentoDaoConfig;
    private final DaoConfig ctlMunicipioDaoConfig;
    private final DaoConfig ctlCantonDaoConfig;
    private final DaoConfig ctlCaserioDaoConfig;
    private final DaoConfig plTipoCapturaDaoConfig;
    private final DaoConfig plTipoActividadDaoConfig;
    private final DaoConfig ctlInstitucionDaoConfig;
    private final DaoConfig ctlTipoEstablecimientoDaoConfig;
    private final DaoConfig ctlEstablecimientoDaoConfig;

    private final UserDao userDao;
    private final BitacoraDao bitacoraDao;
    private final CtlProcedenciaDao ctlProcedenciaDao;
    private final ClaveDao claveDao;
    private final CtlPaisDao ctlPaisDao;
    private final CtlDepartamentoDao ctlDepartamentoDao;
    private final CtlMunicipioDao ctlMunicipioDao;
    private final CtlCantonDao ctlCantonDao;
    private final CtlCaserioDao ctlCaserioDao;
    private final PlTipoCapturaDao plTipoCapturaDao;
    private final PlTipoActividadDao plTipoActividadDao;
    private final CtlInstitucionDao ctlInstitucionDao;
    private final CtlTipoEstablecimientoDao ctlTipoEstablecimientoDao;
    private final CtlEstablecimientoDao ctlEstablecimientoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bitacoraDaoConfig = daoConfigMap.get(BitacoraDao.class).clone();
        bitacoraDaoConfig.initIdentityScope(type);

        ctlProcedenciaDaoConfig = daoConfigMap.get(CtlProcedenciaDao.class).clone();
        ctlProcedenciaDaoConfig.initIdentityScope(type);

        claveDaoConfig = daoConfigMap.get(ClaveDao.class).clone();
        claveDaoConfig.initIdentityScope(type);

        ctlPaisDaoConfig = daoConfigMap.get(CtlPaisDao.class).clone();
        ctlPaisDaoConfig.initIdentityScope(type);

        ctlDepartamentoDaoConfig = daoConfigMap.get(CtlDepartamentoDao.class).clone();
        ctlDepartamentoDaoConfig.initIdentityScope(type);

        ctlMunicipioDaoConfig = daoConfigMap.get(CtlMunicipioDao.class).clone();
        ctlMunicipioDaoConfig.initIdentityScope(type);

        ctlCantonDaoConfig = daoConfigMap.get(CtlCantonDao.class).clone();
        ctlCantonDaoConfig.initIdentityScope(type);

        ctlCaserioDaoConfig = daoConfigMap.get(CtlCaserioDao.class).clone();
        ctlCaserioDaoConfig.initIdentityScope(type);

        plTipoCapturaDaoConfig = daoConfigMap.get(PlTipoCapturaDao.class).clone();
        plTipoCapturaDaoConfig.initIdentityScope(type);

        plTipoActividadDaoConfig = daoConfigMap.get(PlTipoActividadDao.class).clone();
        plTipoActividadDaoConfig.initIdentityScope(type);

        ctlInstitucionDaoConfig = daoConfigMap.get(CtlInstitucionDao.class).clone();
        ctlInstitucionDaoConfig.initIdentityScope(type);

        ctlTipoEstablecimientoDaoConfig = daoConfigMap.get(CtlTipoEstablecimientoDao.class).clone();
        ctlTipoEstablecimientoDaoConfig.initIdentityScope(type);

        ctlEstablecimientoDaoConfig = daoConfigMap.get(CtlEstablecimientoDao.class).clone();
        ctlEstablecimientoDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        bitacoraDao = new BitacoraDao(bitacoraDaoConfig, this);
        ctlProcedenciaDao = new CtlProcedenciaDao(ctlProcedenciaDaoConfig, this);
        claveDao = new ClaveDao(claveDaoConfig, this);
        ctlPaisDao = new CtlPaisDao(ctlPaisDaoConfig, this);
        ctlDepartamentoDao = new CtlDepartamentoDao(ctlDepartamentoDaoConfig, this);
        ctlMunicipioDao = new CtlMunicipioDao(ctlMunicipioDaoConfig, this);
        ctlCantonDao = new CtlCantonDao(ctlCantonDaoConfig, this);
        ctlCaserioDao = new CtlCaserioDao(ctlCaserioDaoConfig, this);
        plTipoCapturaDao = new PlTipoCapturaDao(plTipoCapturaDaoConfig, this);
        plTipoActividadDao = new PlTipoActividadDao(plTipoActividadDaoConfig, this);
        ctlInstitucionDao = new CtlInstitucionDao(ctlInstitucionDaoConfig, this);
        ctlTipoEstablecimientoDao = new CtlTipoEstablecimientoDao(ctlTipoEstablecimientoDaoConfig, this);
        ctlEstablecimientoDao = new CtlEstablecimientoDao(ctlEstablecimientoDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Bitacora.class, bitacoraDao);
        registerDao(CtlProcedencia.class, ctlProcedenciaDao);
        registerDao(Clave.class, claveDao);
        registerDao(CtlPais.class, ctlPaisDao);
        registerDao(CtlDepartamento.class, ctlDepartamentoDao);
        registerDao(CtlMunicipio.class, ctlMunicipioDao);
        registerDao(CtlCanton.class, ctlCantonDao);
        registerDao(CtlCaserio.class, ctlCaserioDao);
        registerDao(PlTipoCaptura.class, plTipoCapturaDao);
        registerDao(PlTipoActividad.class, plTipoActividadDao);
        registerDao(CtlInstitucion.class, ctlInstitucionDao);
        registerDao(CtlTipoEstablecimiento.class, ctlTipoEstablecimientoDao);
        registerDao(CtlEstablecimiento.class, ctlEstablecimientoDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        bitacoraDaoConfig.clearIdentityScope();
        ctlProcedenciaDaoConfig.clearIdentityScope();
        claveDaoConfig.clearIdentityScope();
        ctlPaisDaoConfig.clearIdentityScope();
        ctlDepartamentoDaoConfig.clearIdentityScope();
        ctlMunicipioDaoConfig.clearIdentityScope();
        ctlCantonDaoConfig.clearIdentityScope();
        ctlCaserioDaoConfig.clearIdentityScope();
        plTipoCapturaDaoConfig.clearIdentityScope();
        plTipoActividadDaoConfig.clearIdentityScope();
        ctlInstitucionDaoConfig.clearIdentityScope();
        ctlTipoEstablecimientoDaoConfig.clearIdentityScope();
        ctlEstablecimientoDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BitacoraDao getBitacoraDao() {
        return bitacoraDao;
    }

    public CtlProcedenciaDao getCtlProcedenciaDao() {
        return ctlProcedenciaDao;
    }

    public ClaveDao getClaveDao() {
        return claveDao;
    }

    public CtlPaisDao getCtlPaisDao() {
        return ctlPaisDao;
    }

    public CtlDepartamentoDao getCtlDepartamentoDao() {
        return ctlDepartamentoDao;
    }

    public CtlMunicipioDao getCtlMunicipioDao() {
        return ctlMunicipioDao;
    }

    public CtlCantonDao getCtlCantonDao() {
        return ctlCantonDao;
    }

    public CtlCaserioDao getCtlCaserioDao() {
        return ctlCaserioDao;
    }

    public PlTipoCapturaDao getPlTipoCapturaDao() {
        return plTipoCapturaDao;
    }

    public PlTipoActividadDao getPlTipoActividadDao() {
        return plTipoActividadDao;
    }

    public CtlInstitucionDao getCtlInstitucionDao() {
        return ctlInstitucionDao;
    }

    public CtlTipoEstablecimientoDao getCtlTipoEstablecimientoDao() {
        return ctlTipoEstablecimientoDao;
    }

    public CtlEstablecimientoDao getCtlEstablecimientoDao() {
        return ctlEstablecimientoDao;
    }

}
