package com.minsal.dtic.sinavec.EntityDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ESTABLECIMIENTO_CLAVE".
*/
public class EstablecimientoClaveDao extends AbstractDao<EstablecimientoClave, Long> {

    public static final String TABLENAME = "ESTABLECIMIENTO_CLAVE";

    /**
     * Properties of entity EstablecimientoClave.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property IdClave = new Property(1, long.class, "idClave", false, "ID_CLAVE");
        public final static Property IdEstablecimiento = new Property(2, long.class, "idEstablecimiento", false, "ID_ESTABLECIMIENTO");
    }

    private DaoSession daoSession;


    public EstablecimientoClaveDao(DaoConfig config) {
        super(config);
    }
    
    public EstablecimientoClaveDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ESTABLECIMIENTO_CLAVE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_CLAVE\" INTEGER NOT NULL ," + // 1: idClave
                "\"ID_ESTABLECIMIENTO\" INTEGER NOT NULL ,"+"FOREIGN KEY(\"ID_CLAVE\")" +
                " REFERENCES CLAVE(\"ID\") ON DELETE CASCADE,"+"FOREIGN KEY(\"ID_ESTABLECIMIENTO\")" +
                " REFERENCES CTL_ESTABLECIMIENTO(\"ID\") ON DELETE CASCADE );"); // 2: idEstablecimiento
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ESTABLECIMIENTO_CLAVE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EstablecimientoClave entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdClave());
        stmt.bindLong(3, entity.getIdEstablecimiento());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EstablecimientoClave entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdClave());
        stmt.bindLong(3, entity.getIdEstablecimiento());
    }

    @Override
    protected final void attachEntity(EstablecimientoClave entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EstablecimientoClave readEntity(Cursor cursor, int offset) {
        EstablecimientoClave entity = new EstablecimientoClave( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idClave
            cursor.getLong(offset + 2) // idEstablecimiento
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EstablecimientoClave entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdClave(cursor.getLong(offset + 1));
        entity.setIdEstablecimiento(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EstablecimientoClave entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EstablecimientoClave entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EstablecimientoClave entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getClaveDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCtlEstablecimientoDao().getAllColumns());
            builder.append(" FROM ESTABLECIMIENTO_CLAVE T");
            builder.append(" LEFT JOIN CLAVE T0 ON T.\"ID_CLAVE\"=T0.\"ID\"");
            builder.append(" LEFT JOIN CTL_ESTABLECIMIENTO T1 ON T.\"ID_ESTABLECIMIENTO\"=T1.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected EstablecimientoClave loadCurrentDeep(Cursor cursor, boolean lock) {
        EstablecimientoClave entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Clave clave = loadCurrentOther(daoSession.getClaveDao(), cursor, offset);
         if(clave != null) {
            entity.setClave(clave);
        }
        offset += daoSession.getClaveDao().getAllColumns().length;

        CtlEstablecimiento ctlEstablecimiento = loadCurrentOther(daoSession.getCtlEstablecimientoDao(), cursor, offset);
         if(ctlEstablecimiento != null) {
            entity.setCtlEstablecimiento(ctlEstablecimiento);
        }

        return entity;    
    }

    public EstablecimientoClave loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<EstablecimientoClave> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<EstablecimientoClave> list = new ArrayList<EstablecimientoClave>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<EstablecimientoClave> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<EstablecimientoClave> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
