package com.minsal.dtic.sinavec.EntityDAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PL_COLVOL".
*/
public class PlColvolDao extends AbstractDao<PlColvol, Long> {

    public static final String TABLENAME = "PL_COLVOL";

    /**
     * Properties of entity PlColvol.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Latitud = new Property(1, String.class, "latitud", false, "LATITUD");
        public final static Property Longitud = new Property(2, String.class, "longitud", false, "LONGITUD");
        public final static Property Nombre = new Property(3, String.class, "nombre", false, "NOMBRE");
        public final static Property Estado = new Property(4, Integer.class, "estado", false, "ESTADO");
        public final static Property Clave = new Property(5, String.class, "clave", false, "CLAVE");
        public final static Property IdCaserio = new Property(6, long.class, "idCaserio", false, "ID_CASERIO");
        public final static Property IdSibasi = new Property(7, long.class, "idSibasi", false, "ID_SIBASI");
    }

    private DaoSession daoSession;


    public PlColvolDao(DaoConfig config) {
        super(config);
    }
    
    public PlColvolDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PL_COLVOL\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LATITUD\" TEXT," + // 1: latitud
                "\"LONGITUD\" TEXT," + // 2: longitud
                "\"NOMBRE\" TEXT," + // 3: nombre
                "\"ESTADO\" INTEGER," + // 4: estado
                "\"CLAVE\" TEXT," + // 5: clave
                "\"ID_CASERIO\" INTEGER NOT NULL ," + // 6: idCaserio
                "\"ID_SIBASI\" INTEGER NOT NULL ,"+"FOREIGN KEY(\"ID_CASERIO\")" +
                " REFERENCES CTL_CASERIO(\"ID\") ON DELETE CASCADE,"+"FOREIGN KEY(\"ID_SIBASI\")" +
                " REFERENCES CTL_ESTABLECIMIENTO(\"ID\") ON DELETE CASCADE );"); // 7: idSibasi
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PL_COLVOL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PlColvol entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String latitud = entity.getLatitud();
        if (latitud != null) {
            stmt.bindString(2, latitud);
        }
 
        String longitud = entity.getLongitud();
        if (longitud != null) {
            stmt.bindString(3, longitud);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(4, nombre);
        }
 
        Integer estado = entity.getEstado();
        if (estado != null) {
            stmt.bindLong(5, estado);
        }
 
        String clave = entity.getClave();
        if (clave != null) {
            stmt.bindString(6, clave);
        }
        stmt.bindLong(7, entity.getIdCaserio());
        stmt.bindLong(8, entity.getIdSibasi());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PlColvol entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String latitud = entity.getLatitud();
        if (latitud != null) {
            stmt.bindString(2, latitud);
        }
 
        String longitud = entity.getLongitud();
        if (longitud != null) {
            stmt.bindString(3, longitud);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(4, nombre);
        }
 
        Integer estado = entity.getEstado();
        if (estado != null) {
            stmt.bindLong(5, estado);
        }
 
        String clave = entity.getClave();
        if (clave != null) {
            stmt.bindString(6, clave);
        }
        stmt.bindLong(7, entity.getIdCaserio());
        stmt.bindLong(8, entity.getIdSibasi());
    }

    @Override
    protected final void attachEntity(PlColvol entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PlColvol readEntity(Cursor cursor, int offset) {
        PlColvol entity = new PlColvol( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // latitud
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // longitud
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // nombre
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // estado
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // clave
            cursor.getLong(offset + 6), // idCaserio
            cursor.getLong(offset + 7) // idSibasi
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PlColvol entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLatitud(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLongitud(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNombre(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEstado(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setClave(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIdCaserio(cursor.getLong(offset + 6));
        entity.setIdSibasi(cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PlColvol entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PlColvol entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PlColvol entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCtlCaserioDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCtlEstablecimientoDao().getAllColumns());
            builder.append(" FROM PL_COLVOL T");
            builder.append(" LEFT JOIN CTL_CASERIO T0 ON T.\"ID_CASERIO\"=T0.\"ID\"");
            builder.append(" LEFT JOIN CTL_ESTABLECIMIENTO T1 ON T.\"ID_SIBASI\"=T1.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PlColvol loadCurrentDeep(Cursor cursor, boolean lock) {
        PlColvol entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CtlCaserio ctlCaserio = loadCurrentOther(daoSession.getCtlCaserioDao(), cursor, offset);
         if(ctlCaserio != null) {
            entity.setCtlCaserio(ctlCaserio);
        }
        offset += daoSession.getCtlCaserioDao().getAllColumns().length;

        CtlEstablecimiento ctlEstablecimiento = loadCurrentOther(daoSession.getCtlEstablecimientoDao(), cursor, offset);
         if(ctlEstablecimiento != null) {
            entity.setCtlEstablecimiento(ctlEstablecimiento);
        }

        return entity;    
    }

    public PlColvol loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PlColvol> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PlColvol> list = new ArrayList<PlColvol>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PlColvol> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PlColvol> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
