package com.minsal.dtic.sinavec.EntityDAO;

import org.greenrobot.greendao.annotation.*;

import com.minsal.dtic.sinavec.EntityDAO.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PL_PESQUISA_LARVARIA".
 */
@Entity(active = true)
public class PlPesquisaLarvaria {

    @Id(autoincrement = true)
    private Long id;
    private int idSemanaEpidemiologica;
    private int idUsuarioMod;
    private int idEstado;

    @NotNull
    private java.util.Date fechaHoraReg;

    @NotNull
    private java.util.Date fechaHoraMod;
    private float indiceLarvario;
    private int anophelesDos;
    private int anophelesUno;
    private int culicinosUno;
    private int culicinosDos;
    private int pupa;
    private int numeroCucharonada;
    private float ancho;
    private float largo;

    @NotNull
    private java.util.Date fecha;
    private int estado_sync;
    private long idTablet;
    private long idSibasi;
    private long idCriadero;
    private long idCaserio;
    private long idUsuarioReg;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient PlPesquisaLarvariaDao myDao;

    @ToOne(joinProperty = "idTablet")
    private CtlTablet ctlTablet;

    @Generated
    private transient Long ctlTablet__resolvedKey;

    @ToOne(joinProperty = "idSibasi")
    private CtlEstablecimiento ctlEstablecimiento;

    @Generated
    private transient Long ctlEstablecimiento__resolvedKey;

    @ToOne(joinProperty = "idCriadero")
    private CtlPlCriadero ctlPlCriadero;

    @Generated
    private transient Long ctlPlCriadero__resolvedKey;

    @ToOne(joinProperty = "idCaserio")
    private CtlCaserio ctlCaserio;

    @Generated
    private transient Long ctlCaserio__resolvedKey;

    @ToOne(joinProperty = "idUsuarioReg")
    private FosUserUser fosUserUser;

    @Generated
    private transient Long fosUserUser__resolvedKey;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PlPesquisaLarvaria() {
    }

    public PlPesquisaLarvaria(Long id) {
        this.id = id;
    }

    @Generated
    public PlPesquisaLarvaria(Long id, int idSemanaEpidemiologica, int idUsuarioMod, int idEstado, java.util.Date fechaHoraReg, java.util.Date fechaHoraMod, float indiceLarvario, int anophelesDos, int anophelesUno, int culicinosUno, int culicinosDos, int pupa, int numeroCucharonada, float ancho, float largo, java.util.Date fecha, int estado_sync, long idTablet, long idSibasi, long idCriadero, long idCaserio, long idUsuarioReg) {
        this.id = id;
        this.idSemanaEpidemiologica = idSemanaEpidemiologica;
        this.idUsuarioMod = idUsuarioMod;
        this.idEstado = idEstado;
        this.fechaHoraReg = fechaHoraReg;
        this.fechaHoraMod = fechaHoraMod;
        this.indiceLarvario = indiceLarvario;
        this.anophelesDos = anophelesDos;
        this.anophelesUno = anophelesUno;
        this.culicinosUno = culicinosUno;
        this.culicinosDos = culicinosDos;
        this.pupa = pupa;
        this.numeroCucharonada = numeroCucharonada;
        this.ancho = ancho;
        this.largo = largo;
        this.fecha = fecha;
        this.estado_sync = estado_sync;
        this.idTablet = idTablet;
        this.idSibasi = idSibasi;
        this.idCriadero = idCriadero;
        this.idCaserio = idCaserio;
        this.idUsuarioReg = idUsuarioReg;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPlPesquisaLarvariaDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getIdSemanaEpidemiologica() {
        return idSemanaEpidemiologica;
    }

    public void setIdSemanaEpidemiologica(int idSemanaEpidemiologica) {
        this.idSemanaEpidemiologica = idSemanaEpidemiologica;
    }

    public int getIdUsuarioMod() {
        return idUsuarioMod;
    }

    public void setIdUsuarioMod(int idUsuarioMod) {
        this.idUsuarioMod = idUsuarioMod;
    }

    public int getIdEstado() {
        return idEstado;
    }

    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    @NotNull
    public java.util.Date getFechaHoraReg() {
        return fechaHoraReg;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaHoraReg(@NotNull java.util.Date fechaHoraReg) {
        this.fechaHoraReg = fechaHoraReg;
    }

    @NotNull
    public java.util.Date getFechaHoraMod() {
        return fechaHoraMod;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaHoraMod(@NotNull java.util.Date fechaHoraMod) {
        this.fechaHoraMod = fechaHoraMod;
    }

    public float getIndiceLarvario() {
        return indiceLarvario;
    }

    public void setIndiceLarvario(float indiceLarvario) {
        this.indiceLarvario = indiceLarvario;
    }

    public int getAnophelesDos() {
        return anophelesDos;
    }

    public void setAnophelesDos(int anophelesDos) {
        this.anophelesDos = anophelesDos;
    }

    public int getAnophelesUno() {
        return anophelesUno;
    }

    public void setAnophelesUno(int anophelesUno) {
        this.anophelesUno = anophelesUno;
    }

    public int getCulicinosUno() {
        return culicinosUno;
    }

    public void setCulicinosUno(int culicinosUno) {
        this.culicinosUno = culicinosUno;
    }

    public int getCulicinosDos() {
        return culicinosDos;
    }

    public void setCulicinosDos(int culicinosDos) {
        this.culicinosDos = culicinosDos;
    }

    public int getPupa() {
        return pupa;
    }

    public void setPupa(int pupa) {
        this.pupa = pupa;
    }

    public int getNumeroCucharonada() {
        return numeroCucharonada;
    }

    public void setNumeroCucharonada(int numeroCucharonada) {
        this.numeroCucharonada = numeroCucharonada;
    }

    public float getAncho() {
        return ancho;
    }

    public void setAncho(float ancho) {
        this.ancho = ancho;
    }

    public float getLargo() {
        return largo;
    }

    public void setLargo(float largo) {
        this.largo = largo;
    }

    @NotNull
    public java.util.Date getFecha() {
        return fecha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha(@NotNull java.util.Date fecha) {
        this.fecha = fecha;
    }

    public int getEstado_sync() {
        return estado_sync;
    }

    public void setEstado_sync(int estado_sync) {
        this.estado_sync = estado_sync;
    }

    public long getIdTablet() {
        return idTablet;
    }

    public void setIdTablet(long idTablet) {
        this.idTablet = idTablet;
    }

    public long getIdSibasi() {
        return idSibasi;
    }

    public void setIdSibasi(long idSibasi) {
        this.idSibasi = idSibasi;
    }

    public long getIdCriadero() {
        return idCriadero;
    }

    public void setIdCriadero(long idCriadero) {
        this.idCriadero = idCriadero;
    }

    public long getIdCaserio() {
        return idCaserio;
    }

    public void setIdCaserio(long idCaserio) {
        this.idCaserio = idCaserio;
    }

    public long getIdUsuarioReg() {
        return idUsuarioReg;
    }

    public void setIdUsuarioReg(long idUsuarioReg) {
        this.idUsuarioReg = idUsuarioReg;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public CtlTablet getCtlTablet() {
        long __key = this.idTablet;
        if (ctlTablet__resolvedKey == null || !ctlTablet__resolvedKey.equals(__key)) {
            __throwIfDetached();
            CtlTabletDao targetDao = daoSession.getCtlTabletDao();
            CtlTablet ctlTabletNew = targetDao.load(__key);
            synchronized (this) {
                ctlTablet = ctlTabletNew;
            	ctlTablet__resolvedKey = __key;
            }
        }
        return ctlTablet;
    }

    @Generated
    public void setCtlTablet(CtlTablet ctlTablet) {
        if (ctlTablet == null) {
            throw new DaoException("To-one property 'idTablet' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ctlTablet = ctlTablet;
            idTablet = ctlTablet.getId();
            ctlTablet__resolvedKey = idTablet;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public CtlEstablecimiento getCtlEstablecimiento() {
        long __key = this.idSibasi;
        if (ctlEstablecimiento__resolvedKey == null || !ctlEstablecimiento__resolvedKey.equals(__key)) {
            __throwIfDetached();
            CtlEstablecimientoDao targetDao = daoSession.getCtlEstablecimientoDao();
            CtlEstablecimiento ctlEstablecimientoNew = targetDao.load(__key);
            synchronized (this) {
                ctlEstablecimiento = ctlEstablecimientoNew;
            	ctlEstablecimiento__resolvedKey = __key;
            }
        }
        return ctlEstablecimiento;
    }

    @Generated
    public void setCtlEstablecimiento(CtlEstablecimiento ctlEstablecimiento) {
        if (ctlEstablecimiento == null) {
            throw new DaoException("To-one property 'idSibasi' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ctlEstablecimiento = ctlEstablecimiento;
            idSibasi = ctlEstablecimiento.getId();
            ctlEstablecimiento__resolvedKey = idSibasi;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public CtlPlCriadero getCtlPlCriadero() {
        long __key = this.idCriadero;
        if (ctlPlCriadero__resolvedKey == null || !ctlPlCriadero__resolvedKey.equals(__key)) {
            __throwIfDetached();
            CtlPlCriaderoDao targetDao = daoSession.getCtlPlCriaderoDao();
            CtlPlCriadero ctlPlCriaderoNew = targetDao.load(__key);
            synchronized (this) {
                ctlPlCriadero = ctlPlCriaderoNew;
            	ctlPlCriadero__resolvedKey = __key;
            }
        }
        return ctlPlCriadero;
    }

    @Generated
    public void setCtlPlCriadero(CtlPlCriadero ctlPlCriadero) {
        if (ctlPlCriadero == null) {
            throw new DaoException("To-one property 'idCriadero' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ctlPlCriadero = ctlPlCriadero;
            idCriadero = ctlPlCriadero.getId();
            ctlPlCriadero__resolvedKey = idCriadero;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public CtlCaserio getCtlCaserio() {
        long __key = this.idCaserio;
        if (ctlCaserio__resolvedKey == null || !ctlCaserio__resolvedKey.equals(__key)) {
            __throwIfDetached();
            CtlCaserioDao targetDao = daoSession.getCtlCaserioDao();
            CtlCaserio ctlCaserioNew = targetDao.load(__key);
            synchronized (this) {
                ctlCaserio = ctlCaserioNew;
            	ctlCaserio__resolvedKey = __key;
            }
        }
        return ctlCaserio;
    }

    @Generated
    public void setCtlCaserio(CtlCaserio ctlCaserio) {
        if (ctlCaserio == null) {
            throw new DaoException("To-one property 'idCaserio' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ctlCaserio = ctlCaserio;
            idCaserio = ctlCaserio.getId();
            ctlCaserio__resolvedKey = idCaserio;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public FosUserUser getFosUserUser() {
        long __key = this.idUsuarioReg;
        if (fosUserUser__resolvedKey == null || !fosUserUser__resolvedKey.equals(__key)) {
            __throwIfDetached();
            FosUserUserDao targetDao = daoSession.getFosUserUserDao();
            FosUserUser fosUserUserNew = targetDao.load(__key);
            synchronized (this) {
                fosUserUser = fosUserUserNew;
            	fosUserUser__resolvedKey = __key;
            }
        }
        return fosUserUser;
    }

    @Generated
    public void setFosUserUser(FosUserUser fosUserUser) {
        if (fosUserUser == null) {
            throw new DaoException("To-one property 'idUsuarioReg' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.fosUserUser = fosUserUser;
            idUsuarioReg = fosUserUser.getId();
            fosUserUser__resolvedKey = idUsuarioReg;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
