package com.minsal.dtic.sinavec.EntityDAO;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RESULTADO_GOTA".
 */
@Entity
public class ResultadoGota {

    @Id
    private Long id;
    private String resultado;
    private String codigo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ResultadoGota() {
    }

    public ResultadoGota(Long id) {
        this.id = id;
    }

    @Generated
    public ResultadoGota(Long id, String resultado, String codigo) {
        this.id = id;
        this.resultado = resultado;
        this.codigo = codigo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResultado() {
        return resultado;
    }

    public void setResultado(String resultado) {
        this.resultado = resultado;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
